---
name: goreleaser rust
on:
  workflow_call:
    inputs:
      draft:
        required: false
        type: boolean
        default: true
      release:
        required: false
        type: boolean
        default: true

permissions: {}

jobs:
  goreleaser:
    timeout-minutes: 30
    runs-on: macos-latest
    outputs:
      hashes: ${{ steps.binary.outputs.hashes }}
    permissions:
      contents: write
      id-token: write
      attestations: write
    steps:
      - uses: actions/checkout@8e8c483db84b4bee98b60c0593521ed34d9990e8 # v6.0.1
        with:
          fetch-depth: 0
      - name: Setup Zig
        uses: mlugg/setup-zig@fa65c4058643678a4e4a9a60513944a7d8d35440 # v2.1.0
      - name: Install cosign
        uses: sigstore/cosign-installer@faadad0cce49287aee09b3a48701e75088a2c6ad # v4.0.0
      - name: Install syft
        uses: anchore/sbom-action/download-syft@a930d0ac434e3182448fe678398ba5713717112a # v0.21.0
      - name: Install Mingw-w64
        run: brew install mingw-w64
      - name: Run goreleaser
        uses: goreleaser/goreleaser-action@e435ccd777264be153ace6237001ef4d979d3a7a # v6.4.0
        id: goreleaser
        with:
          args: release --clean
        env:
          GITHUB_TOKEN: ${{ github.token }}
      - name: Generate binary hashes
        id: binary
        env:
          ARTIFACTS: ${{ steps.goreleaser.outputs.artifacts }}
        run: |
          set -euo pipefail

          checksum_file=$(echo "$ARTIFACTS" | jq -r '.[] | select (.type=="Checksum") | .path')
          echo "hashes=$(cat "$checksum_file" | base64 -w0)" >> "$GITHUB_OUTPUT"
      - uses: actions/attest-build-provenance@00014ed6ed5efc5b1ab7f7f34a39eb55d41aa4f8 # v3.1.0
        with:
          subject-path: |
            dist/*.tar.gz
            dist/*.zip
            dist/*.txt
            dist/*.sigstore.json
            dist/*.sbom.json

  binary-provenance:
    needs: [goreleaser]
    permissions:
      actions: read
      id-token: write
      contents: write
    # slsa-framework/slsa-github-generator doesn't support pinning versions via commit SHA yet
    # https://github.com/slsa-framework/slsa-github-generator/issues/722
    uses: slsa-framework/slsa-github-generator/.github/workflows/generator_generic_slsa3.yml@v2.1.0
    with:
      base64-subjects: ${{ needs.goreleaser.outputs.hashes }}
      upload-assets: true
      draft-release: ${{ inputs.draft }}

  publish-release:
    if: ${{ inputs.draft && inputs.release }}
    needs: [binary-provenance]
    runs-on: ubuntu-latest
    permissions:
      contents: write
    steps:
      - name: Publish release
        env:
          GITHUB_TOKEN: ${{ github.token }}
        run: |
          gh -R "$GITHUB_REPOSITORY" release edit "$GITHUB_REF_NAME" --draft=false

  binary-verify:
    if: ${{ (!inputs.draft || inputs.release) && ! failure() }}
    needs: [goreleaser, binary-provenance, publish-release]
    runs-on: ubuntu-latest
    env:
      CHECKSUMS: ${{ needs.goreleaser.outputs.hashes }}
      PROVENANCE: ${{ needs.binary-provenance.outputs.provenance-name }}
    steps:
      - name: Install SLSA verifier
        uses: slsa-framework/slsa-verifier/actions/installer@ea584f4502babc6f60d9bc799dbbb13c1caa9ee6 # v2.7.1
      - name: Download assets
        env:
          GITHUB_TOKEN: ${{ github.token }}
        run: |
          set -euo pipefail
          # shellcheck disable=SC2153
          checksums=$(echo "$CHECKSUMS" | base64 -d)
          while read -r line; do
            fn=$(awk '{print $2}' <<<"$line")
            echo "Downloading $fn"
            gh -R "$GITHUB_REPOSITORY" release download "$GITHUB_REF_NAME" -p "$fn"
          done <<<"$checksums"
          echo "Downloading provenance $PROVENANCE"
          gh -R "$GITHUB_REPOSITORY" release download "$GITHUB_REF_NAME" -p "$PROVENANCE"
      - name: Verify assets
        run: |
          set -euo pipefail
          # shellcheck disable=SC2153
          checksums=$(echo "$CHECKSUMS" | base64 -d)
          while read -r line; do
            fn=$(awk '{print $2}' <<<"$line")
            echo "Verifying $fn"
            slsa-verifier verify-artifact --provenance-path "$PROVENANCE" \
                                          --source-uri "github.com/$GITHUB_REPOSITORY" \
                                          --source-tag "$GITHUB_REF_NAME" \
                                          "$fn"
          done <<<"$checksums"
